name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # ou master selon ton dépôt

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate version file
      run: |
        echo "App: vicetogo.karuidesu.org" > version.txt
        echo "Commit: $GITHUB_SHA" >> version.txt
        echo "Date: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> version.txt


    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: ./        # dossier local à déployer
        server-dir: /     # dossier distant sur Hostinger  //ajouter en public_html/vicetogo quand ce sera prêt
