name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --prefix frontend  # Installation des dépendances uniquement pour le frontend

      - name: Build project
        run: npm run build --prefix frontend  # Build du frontend (Next.js)

      - name: Export Next.js app (si tu utilises next export)
        run: npm run export --prefix frontend  # Si tu utilises `next export` pour créer une version statique
          
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./frontend/out    # Point vers le dossier de sortie de Next.js
          server-dir: /public_html/vicetogo/   # Dossier sur Hostinger
